name: Node.js Package

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
        version: 1.0.0
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
        working-directory: ./source/javascript
      - run: npm ci
        working-directory: ./source/javascript
      - run: npm test
        working-directory: ./source/javascript

  publish-npm:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/
      - run: npm ci
        working-directory: ./source/javascript
      - run: npm publish
        working-directory: ./source/javascript
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
